sudo: required

services: 
- docker

before_install:
 - docker build -t navs4/docker-react  -f Dockerfile.dev .


script:
  - docker run -e CI=true navs4/docker-react  npm run test


deploy:
 provider: elasticbeanstalk
 region: us-east-1
 app: Frontend
 env: Frontend-env
 bucket-name:  elasticbeanstalk-us-east-1-557306256516
 bucket-path: Frontend
 on:
  branch: main
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key: $AWS_SECRET_KEY


 
 


