version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes:
      - /app/node_modules
      - /c/Naveen Personal Apps/UI/docker/frontend:/app
  test:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    command: ["npm", "run", "test"]
       
